name: Data Ingestion and Transformation Tests

on:
  push:
    paths-ignore:
      - 'README.md'  # Ignore changes to README.md

jobs:
  data_ingestion_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run data ingestion tests
        run: |
          pytest tests/test_data_ingestion.py

  data_transformation_test:
    runs-on: ubuntu-latest
    needs: data_ingestion_test
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run data transformation tests
        run: |
          pytest tests/test_data_transformation.py