name: Data Ingestion, Transformation, and Model Trainer Tests

on:
  push:
    paths-ignore:
      - 'README.md'  # Ignore changes to README.md

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run data ingestion tests
        run: |
          pytest tests/test_data_ingestion.py
      - name: Run data transformation tests
        run: |
          pytest tests/test_data_transformation.py
      - name: Run model trainer tests
        run: |
          pytest tests/test_model_trainer.py